services:
    dmzx.totalavtiveext.listener:
        class: dmzx\totalavtiveext\event\listener
        arguments:
            - @template
            - @user
            - @dbal.conn
        tags:
            - { name: event.listener }
